# Generated by Django 5.0.6 on 2024-05-15 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c942e3c-a0a6-463c-bb91-1a856f5a54a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
