# Generated by Django 5.0.6 on 2024-05-15 04:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0faa7f43-23f7-42dd-8851-36c049da7134'), editable=False, primary_key=True, serialize=False),
        ),
    ]
