# Generated by Django 5.0.6 on 2024-05-15 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efa9e7f8-b5b1-42bb-b756-176712a4081d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
