# Generated by Django 5.0.6 on 2024-05-15 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6c4eac6-a24a-42db-b130-cc1dfb654888'), editable=False, primary_key=True, serialize=False),
        ),
    ]
