# Generated by Django 5.0.6 on 2024-05-15 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02fb5fb7-0dc8-4519-b245-aa9cc3e5ddb1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
