# Generated by Django 5.0.6 on 2024-05-15 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2525bd0d-67cb-477e-8e2d-07813089839b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
