# Generated by Django 5.0.6 on 2024-05-15 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4755d6f-9f2e-4914-96b8-21dcd40891b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
