# Generated by Django 5.0.6 on 2024-05-15 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('889bcaa6-0a51-48c6-a2bf-1e2b6f4af156'), editable=False, primary_key=True, serialize=False),
        ),
    ]
