# Generated by Django 5.0.6 on 2024-05-16 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e57357b-bf7c-43e4-9b64-624855ca2a4e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
