# Generated by Django 5.0.6 on 2024-05-16 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('415f0774-2fc0-4220-bb7e-b7300548955e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
