# Generated by Django 5.0.6 on 2024-05-16 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4432b39b-29bd-4dff-a240-e550685b2788'), editable=False, primary_key=True, serialize=False),
        ),
    ]
