# Generated by Django 5.0.6 on 2024-05-16 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ee0e7d4d-e707-4821-b2c9-3598e332bc98'), editable=False, primary_key=True, serialize=False),
        ),
    ]
