# Generated by Django 5.0.6 on 2024-05-16 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd9eaa64-e548-4e6d-9d2e-2055ae5e7db2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
