# Generated by Django 5.0.6 on 2024-05-16 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d388c233-a844-4e7f-88b6-036caa581042'), editable=False, primary_key=True, serialize=False),
        ),
    ]
