# Generated by Django 5.0.6 on 2024-05-16 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e0ef48d-ff5a-4f56-a52a-6933bcc859a3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
