# Generated by Django 5.0.6 on 2024-05-16 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a957325d-8791-4895-a96f-c36b020ae393'), editable=False, primary_key=True, serialize=False),
        ),
    ]
