# Generated by Django 5.0.6 on 2024-05-16 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d07a2ac-9ab1-4248-b178-43bcffd5d801'), editable=False, primary_key=True, serialize=False),
        ),
    ]
