# Generated by Django 5.0.6 on 2024-05-16 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0021_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('778b1cb4-0f13-4adf-9d67-c45a9fc66776'), editable=False, primary_key=True, serialize=False),
        ),
    ]
