# Generated by Django 5.0.6 on 2024-05-16 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0022_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c8409ae9-6a55-4f7a-bfd2-dd832d0ce2cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
