# Generated by Django 5.0.6 on 2024-05-16 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0023_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65535b48-9a12-4de0-9bcd-22933da5f474'), editable=False, primary_key=True, serialize=False),
        ),
    ]
