# Generated by Django 5.0.6 on 2024-05-16 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0024_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b849066d-87b0-49a5-9c54-7fe6c8121e64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
