# Generated by Django 5.0.6 on 2024-05-16 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0025_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c30e8f7b-208b-4f88-b7ff-cb6ef17cc755'), editable=False, primary_key=True, serialize=False),
        ),
    ]
