# Generated by Django 5.0.6 on 2024-05-16 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0026_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('743286f6-7a3e-48ea-b417-9828327e4882'), editable=False, primary_key=True, serialize=False),
        ),
    ]
