# Generated by Django 5.0.6 on 2024-05-16 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0027_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62ef2467-2989-44d0-8ed7-2bb4702c99b6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
