# Generated by Django 5.0.6 on 2024-05-15 04:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4eb9c9e0-90a8-41c2-beb9-70677ab0e425'), editable=False, primary_key=True, serialize=False),
        ),
    ]
