# Generated by Django 5.0.6 on 2024-05-15 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c278e6c1-6ad0-47d1-9b5d-ad3943555a0f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
