# Generated by Django 5.0.6 on 2024-05-15 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4a93e2a-dedb-485c-b0d5-bcd41fd403e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
