# Generated by Django 5.0.6 on 2024-05-15 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca7622cb-87eb-4988-8584-9ed23df37f61'), editable=False, primary_key=True, serialize=False),
        ),
    ]
