# Generated by Django 5.0.6 on 2024-05-15 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54315e5b-0c12-4ba1-959b-f9020bdbdeb6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
