# Generated by Django 5.0.6 on 2024-05-15 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c418007-4850-4731-a520-6d5ffd834673'), editable=False, primary_key=True, serialize=False),
        ),
    ]
