# Generated by Django 5.0.6 on 2024-05-15 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20b4471e-9571-42da-bfa2-9c9bad421f84'), editable=False, primary_key=True, serialize=False),
        ),
    ]
