# Generated by Django 5.0.6 on 2024-05-16 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b65ea405-caa4-4d83-9f2a-362deab19fd5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
