# Generated by Django 5.0.6 on 2024-05-16 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adb72497-cd19-4848-9339-2cfd196cc88f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
