# Generated by Django 5.0.6 on 2024-05-16 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9bf8bb5-e43f-4bac-8e7b-60ce4f77d5c4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
