# Generated by Django 5.0.6 on 2024-05-16 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7baddeea-aab6-40c2-867d-6a1b9b84ad38'), editable=False, primary_key=True, serialize=False),
        ),
    ]
