# Generated by Django 5.0.6 on 2024-05-16 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6abb0e57-471f-4d8c-a76e-77bce46b7ccd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
