# Generated by Django 5.0.6 on 2024-05-16 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9282e402-ac62-4fb2-9361-e58dfdc69120'), editable=False, primary_key=True, serialize=False),
        ),
    ]
