# Generated by Django 5.0.6 on 2024-05-16 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66cd7d2c-e369-4e6d-ba0b-c56fa957c1b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
