# Generated by Django 5.0.6 on 2024-05-16 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb651f19-9b47-4e18-ae37-4dcbe934bfd3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
