# Generated by Django 5.0.6 on 2024-05-16 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4eb47b6d-a2f0-4d48-b50e-53c59877eeb0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
