# Generated by Django 5.0.6 on 2024-05-16 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f695f93-26e4-48c7-8c6b-dc00f4083224'), editable=False, primary_key=True, serialize=False),
        ),
    ]
