# Generated by Django 5.0.6 on 2024-05-16 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a692c3f-f20c-467d-9fe1-65404881026d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
