# Generated by Django 5.0.6 on 2024-05-16 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbf36495-7463-49c9-9c6f-42a1fc02e28e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
