# Generated by Django 5.0.6 on 2024-05-16 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47798d16-6ebb-45bd-a9ea-ab3827a43801'), editable=False, primary_key=True, serialize=False),
        ),
    ]
