# Generated by Django 5.0.6 on 2024-05-16 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb5faed1-aacd-45dc-b34d-ecf113764bff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
