# Generated by Django 5.0.6 on 2024-05-16 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49fb4b49-1f16-40bd-a852-2019bd6ea07e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
