# Generated by Django 5.0.6 on 2024-05-16 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f17a19b-ef9c-4b15-9634-0f83bdeea123'), editable=False, primary_key=True, serialize=False),
        ),
    ]
