# Generated by Django 5.0.6 on 2024-05-16 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e0ba797-a203-402e-87d3-5d24aa45c096'), editable=False, primary_key=True, serialize=False),
        ),
    ]
