# Generated by Django 5.0.6 on 2024-05-16 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d81eff3-b23e-47b6-a5d1-dedbc29eef1e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
