# Generated by Django 5.0.6 on 2024-05-16 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62f8a6e5-e128-4df3-9d84-dfc01b100d14'), editable=False, primary_key=True, serialize=False),
        ),
    ]
