# Generated by Django 5.0.6 on 2024-05-16 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5be58f7-5111-4704-bc2a-94d3d2d4d561'), editable=False, primary_key=True, serialize=False),
        ),
    ]
