# Generated by Django 5.0.6 on 2024-05-16 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29113144-d7e9-4a9a-8d29-475d2d2d104c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
