# Generated by Django 5.0.6 on 2024-05-16 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08e8ae77-953c-4e85-ad27-87864c6296ef'), editable=False, primary_key=True, serialize=False),
        ),
    ]
