# Generated by Django 5.0.6 on 2024-05-17 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8ec08ea-2844-401a-99e9-a136186f4beb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
