# Generated by Django 5.0.6 on 2024-05-17 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e23435e7-57b6-434e-898c-fb46a3e499f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
