# Generated by Django 5.0.6 on 2024-05-17 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cbd6a26f-b1a0-470e-b594-3e0ceaff0d21'), editable=False, primary_key=True, serialize=False),
        ),
    ]
