# Generated by Django 5.0.6 on 2024-05-17 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f28b0e5-84ea-4092-9b1d-ca60a075884a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
