# Generated by Django 5.0.6 on 2024-05-17 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('140dc32b-4696-4a9e-9c7e-d51811ca16f4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
