# Generated by Django 5.0.2 on 2024-05-17 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb6de0ff-474b-418c-a15c-7fdc651b9fdf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
