# Generated by Django 5.0.2 on 2024-05-17 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('103b54c2-4c11-4bff-a95f-4a8a92e81da2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
