# Generated by Django 5.0.2 on 2024-05-17 04:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4fccdd4b-4fb7-4f58-8ced-6cb7b58654b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
