# Generated by Django 5.0.2 on 2024-05-18 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51302154-99a7-4c7c-ba19-dda47464f8e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
