# Generated by Django 5.0.2 on 2024-05-18 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f7f03c7-d22b-4d88-b7c4-28fc4f372bed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
