# Generated by Django 5.0.2 on 2024-05-18 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e2176ae-6e7c-45ba-a017-453db8376c63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
