# Generated by Django 5.0.2 on 2024-05-18 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0044_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bb8cb4b-d63c-4627-94f8-d788a54cb676'), editable=False, primary_key=True, serialize=False),
        ),
    ]
