# Generated by Django 5.0.2 on 2024-05-19 01:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f23c636-e6c2-4006-96a1-09dfe80255b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
