# Generated by Django 5.0.2 on 2024-05-19 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0046_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3360f1af-eb79-47d5-b716-8ec17671d8b4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
