# Generated by Django 5.0.2 on 2024-05-19 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_alter_property_id_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd8c9bd4-67e0-4636-920a-bf7b01106e81'), editable=False, primary_key=True, serialize=False),
        ),
    ]
