# Generated by Django 5.0.2 on 2024-05-19 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79a93de5-cd89-40cd-a0a6-d7363564a6e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
