# Generated by Django 5.0.2 on 2024-05-19 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0050_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af45981f-ea73-4025-b31f-c474d8a1d9ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
