# Generated by Django 5.0.2 on 2024-05-20 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3460089a-d078-4974-ac0c-b9b488c2e654'), editable=False, primary_key=True, serialize=False),
        ),
    ]
