# Generated by Django 5.0.2 on 2024-05-20 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0052_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed7e9bfa-2eca-4a4c-8b58-4717fe37e123'), editable=False, primary_key=True, serialize=False),
        ),
    ]
