# Generated by Django 5.0.2 on 2024-05-20 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0053_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a72adac4-e6a9-4d56-85cb-ac5f4e270d16'), editable=False, primary_key=True, serialize=False),
        ),
    ]
