# Generated by Django 5.0.2 on 2024-05-20 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7062721-5ca4-4931-84c1-fcfcb8e7316f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
