# Generated by Django 5.0.2 on 2024-05-20 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0055_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6a8d29e-3685-4331-a566-99edfcee248c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
