# Generated by Django 5.0.2 on 2024-05-20 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0056_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7631351-8200-4c5b-80cd-f7ea8e324d2f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
