# Generated by Django 5.0.2 on 2024-05-21 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0057_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e66731d-c361-4be5-84fe-89d1389f1d59'), editable=False, primary_key=True, serialize=False),
        ),
    ]
