# Generated by Django 5.0.2 on 2024-05-21 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0059_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ee641abf-0d65-47af-bc3c-a5cb04be736e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
