# Generated by Django 5.0.2 on 2024-05-21 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0062_remove_reservation_favorited_property_favorited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ef56406-d68b-4a41-8baf-f2c2d41e4ccb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
