# Generated by Django 5.0.2 on 2024-05-21 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0063_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a8c5dd8-9d09-40a6-912e-563162ca06c6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
