# Generated by Django 5.0.2 on 2024-05-21 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0064_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22287467-9139-40b2-8ed5-ac494f474a18'), editable=False, primary_key=True, serialize=False),
        ),
    ]
