# Generated by Django 5.0.2 on 2024-05-22 01:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0065_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f29536a-624a-4c48-8f99-2e1ba2fb42c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
