# Generated by Django 5.0.2 on 2024-05-22 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0067_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec289655-ee58-4f8e-92dc-c5d3f4f3ac9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
