# Generated by Django 5.0.2 on 2024-05-22 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0068_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bcea2358-d6c7-4985-bea6-0225bd8ceaed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
