# Generated by Django 5.0.2 on 2024-05-22 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0069_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f661800b-704f-4334-9612-7639a907f8cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
