# Generated by Django 5.0.2 on 2024-05-22 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0070_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4a5932a-3a69-42c9-863a-2e884a449e48'), editable=False, primary_key=True, serialize=False),
        ),
    ]
