# Generated by Django 5.0.2 on 2024-05-25 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0071_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc129f4c-bb83-44a9-9e2e-584ac334110b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
