# Generated by Django 5.0.2 on 2024-05-26 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0072_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17260b7b-48a6-421e-8f83-ca59c3ad30a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
