# Generated by Django 5.0.2 on 2024-05-26 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0073_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad90b2c1-c137-4ac5-9a8c-f3063067de75'), editable=False, primary_key=True, serialize=False),
        ),
    ]
