# Generated by Django 5.0.2 on 2024-05-27 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0075_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1d04173-bae9-4a1b-98aa-decab44584f9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
