# Generated by Django 5.0.2 on 2024-05-27 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0076_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('748000fb-939b-49df-be80-e73db956bc39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
