# Generated by Django 5.0.2 on 2024-05-28 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0077_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e46a7ed8-0e61-4e54-94d3-7c8165d38ddf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
