# Generated by Django 5.0.2 on 2024-05-29 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0078_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c90534d-af05-4d2f-b42d-709eca77ec90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
