# Generated by Django 5.0.2 on 2024-05-30 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0079_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab5f5d0e-6fbe-4c8a-8dc3-3c55ca5a2d7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
