# Generated by Django 5.0.2 on 2024-05-31 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0081_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fae96e6-f5f2-4718-a044-b63dbf7cee55'), editable=False, primary_key=True, serialize=False),
        ),
    ]
