# Generated by Django 5.0.2 on 2024-05-31 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0083_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47e668f2-389e-42f9-8579-a164187c9bee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
