# Generated by Django 5.0.2 on 2024-05-31 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0084_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86772058-8389-457b-b7d0-418887b4f489'), editable=False, primary_key=True, serialize=False),
        ),
    ]
