# Generated by Django 5.0.2 on 2024-05-31 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0085_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.UUID('091ba7cb-dfac-4e5f-976c-4b7e5f258fe7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
